export const REGISTER_START = 'REGISTOR_START';
export const REGISTER_SUCCESS = 'REGISTOR_SUCCESS';
export const REGISTER_ERROR = 'REGISTOR_ERROR';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
